language: java
sudo: false

git:
  submodules: false

install: true
script: "./travis.sh"
env:
  - TEST=CI
matrix:
  fast_finish: true

before_cache:
  # remove all the artifacts that are installed in local repo because of mvn deploy
  - rm -rf $HOME/.m2/repository/org/sonarsource/java
  - find $HOME/.m2 -name resolver-status.properties -exec rm {} \;
cache:
  directories:
    - '$HOME/.m2/repository'
    - '$HOME/.sonar'
    - '$HOME/jvm'
    - '$HOME/maven'

notifications:
  email: false
  hipchat:
    rooms:
      secure: eZCNoMOh1nR+aTJsnroK7DWHgurwtQoOunNeC0pIAURne4Y7Rlztcn2uOGgqCzSZfn0ucV8Z7RSMp2ANOW7tiAYoF86/an/JoP5wnEyLo3aQFg6Dakw5gdFBfnQpVMatNAVgJDVcqhsjCR0WJy6vo0Re8y1Cm1409hJb+lCjhsM=
    template:
      - '<a href="%{build_url}">SonarJava#%{build_number}</a> - <a href="https://github.com/%{repository_slug}/tree/%{branch}">%{branch}</a> - <a href="%{compare_url}">%{commit}</a> %{commit_message} by %{author}'
    format: html  
    notify: true
  webhooks:
    urls:
      - secure: jioMmc06IBRAgbWiyUP8T0ZsWPn+QhAf/UoGocYo5la20RMMb0M5A5Lpl7yvyGFv+PmC2SIlG3FHf61nRvHNaq1zSWGwOgmGZUrhz/tCD3caSB+BJoba46pcYL/W/V7X2nXMzhJiCbU3U4JoGwVUYqt3Ug1Jl/oLBk2IUp2U0zg=
    on_start: always
