language: java
sudo: false

jdk:
  - oraclejdk7

install: true
script: ./travis.sh
env:
  - TESTS=CI
  - TESTS=IT-DEV
  - TESTS=IT-LTS
matrix:
  fast_finish: true
  include:
    - jdk: oraclejdk8
      env: TESTS=RULING PROJECT=fluent_http
    - jdk: oraclejdk8
      env: TESTS=RULING PROJECT=apache_commons_beanutils
    - jdk: oraclejdk8
      env: TESTS=RULING PROJECT=guava
    - jdk: oraclejdk8
      env: TESTS=RULING PROJECT=jdk7

cache:
  directories:
    - '$HOME/.m2/repository'

notifications:
  email: false
