name: Prepare Next Development Iteration

on:
  workflow_dispatch:
    inputs:
      nextVersion:
        description: Version number of the next iteration
        required: true

jobs:
  Next-Iteration-Job:
    name: Next Iteration Job
    runs-on: github-ubuntu-latest-s
    permissions:
      pull-requests: write
      contents: write

    steps:

      - name: Checkout Sources
        uses: actions/checkout@v4

      - name: Update Version Number
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NEXT_VERSION: ${{ inputs.nextVersion }}
        run: |
          git config user.name "${GITHUB_ACTOR}"
          git config user.email "${GITHUB_ACTOR}@users.noreply.github.com"
          git checkout -b gh-action/next-iteration
          mvn versions:set -DgenerateBackupPoms=false -DnewVersion="${NEXT_VERSION}"
          git commit -m 'Prepare next development iteration' -a
          git push --set-upstream origin gh-action/next-iteration
          gh pr create -B master --title 'Prepare next development iteration' --body ''
