name: Update Rule Metadata

on: workflow_dispatch

jobs:
  UpdateRuleMetadata_job:
    name: Update Rule Metadata
    runs-on: github-ubuntu-latest-s
    permissions:
      pull-requests: write
      contents: write
      id-token: write

    steps:
      - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
      - uses: ./.github/actions/update-rule-metadata
        with:
          post-update: |
            sed --in-place='' -e 's/rule:java:S3649/rule:javasecurity:S3649/g' 'sonar-java-plugin/src/main/resources/org/sonar/l10n/java/rules/java/S2077.html'
